apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: webapp
  template:
    metadata:
      labels:
        component: webapp
    spec:
      containers:
      - name: webapp
        image: socialcomputing/coursemapper-webserver-webapp
        ports:
        - containerPort: 4200
        env:
        - name: BASE_URL
          value: "/api"
        readinessProbe:
          httpGet:
            path: /
            port: 4200
        livenessProbe:
          httpGet:
            path: /
            port: 4200
          periodSeconds: 60
          timeoutSeconds: 5
