apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: coursemapper-webserver-

labels:
- includeSelectors: true
  pairs:
    app: coursemapper-webserver

configMapGenerator:
- name: ingress
  literals:
  - host=example.org

secretGenerator:
- name: webserver
  literals:
  - COOKIE_SECRET=secret
  - JWT_SECRET=secret
  - PASS=adminpassword

images:
- name: mongo
  newTag: "6.0"
- name: socialcomputing/coursemapper-webserver-webapp
  newTag: latest
- name: socialcomputing/coursemapper-webserver-webserver
  newTag: latest

vars:
- name: MONGODB_SERVICE
  objref:
    apiVersion: v1
    kind: Service
    name: mongodb
  fieldref: {}
- name: FQDN
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: ingress
  fieldref:
    fieldpath: data.host

resources:
- ingress.yaml
- webapp/deployment.yaml
- webapp/service.yaml
- webserver/deployment.yaml
- webserver/service.yaml
- webserver/pvc.yaml
- mongodb/deployment.yaml
- mongodb/service.yaml
- mongodb/pvc.yaml
