version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "[CI] "

- package-ecosystem: "docker"
  directory: "/webapp"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "[Dockerfile] "
  labels:
  - "dependencies"
  - "docker"
  - "webapp"

- package-ecosystem: "docker"
  directory: "/webserver"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "[Dockerfile] "
  labels:
  - "dependencies"
  - "docker"
  - "webserver"

- package-ecosystem: "npm"
  directory: "/webapp"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
  commit-message:
    prefix: "[webapp] "
  labels:
  - "dependencies"
  - "npm"
  - "webapp"

- package-ecosystem: "npm"
  directory: "/webserver"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
  commit-message:
    prefix: "[webserver] "
  labels:
  - "dependencies"
  - "npm"
  - "webserver"
