apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: coursemapper-webserver-
commonLabels:
  app: coursemapper-webserver

vars:
- name: MONGODB_SERVICE
  objref:
    apiVersion: v1
    kind: Service
    name: mongodb

secretGenerator:
- name: webserver
  literals:
  - COOKIE_SECRET=secret
  - JWT_SECRET=secret
  - PASS=adminpassword

resources:
- ingress.yaml
- webapp/deployment.yaml
- webapp/service.yaml
- webserver/deployment.yaml
- webserver/service.yaml
- webserver/pvc.yaml
- mongodb/deployment.yaml
- mongodb/service.yaml
- mongodb/pvc.yaml
