version: "3"

services:
  webapp:
    image: coursemapper-webserver-webapp
    build:
      context: webapp
    environment:
      BASE_URL: http://127.0.0.1:8080
    ports:
      - "4200:4200"
    depends_on:
      - webserver

  webserver:
    image: coursemapper-webserver-webserver
    build:
      context: webserver
    environment:
      - PORT=8080
      - COOKIE_SECRET=secret
      - JWT_SECRET=secret
      - PASS=adminpassword
      - MONGO_DB=mongodb://mongo:27017/coursemapper
    ports:
      - "8080:8080"
    volumes:
      - webserver-uploads:/app/public/uploads
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    volumes:
      - mongo:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      start_period: 2s
      interval: 10s

volumes:
  mongo:
  webserver-uploads:
