apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases: [../base]

namespace: sc

secretGenerator:
- name: webserver
  behavior: merge
  literals:
  - COOKIE_SECRET=secret
  - JWT_SECRET=secret
  - PASS=admin

images:
- name: socialcomputing/coursemapper-webserver-webapp
  newTag: latest
- name: socialcomputing/coursemapper-webserver-webserver
  newTag: latest

patches:
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Never
