services:
  preprocess:
    platform: linux/x86_64
    build: .
    environment:
      - POSTGRES_PASSWORD: password
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
