name: CI

on:
  push:
    tags:       [ v*.*.* ]
    branches:   [ main, development ]
  pull_request:
    branches:   [ main, development ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      services:        "[ 'webapp', 'webserver' ]"
      base_image_name: "socialcomputing/coursemapper-webserver-"
      push:            ${{ github.event_name != 'pull_request' }}
    secrets:
      registry_user:   ${{ secrets.DOCKERHUB_USERNAME }}
      registry_token:  ${{ secrets.DOCKERHUB_TOKEN }}

  check:
    uses:  ./.github/workflows/check.yml

  release:
    needs: [ build, check ]
    if:    github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    uses:  ./.github/workflows/release.yml
