name: Kustomize
on:   [ workflow_call ]
jobs:
  check:
    name:      Validate manifests
    runs-on:   ubuntu-latest
    container: deck15/kubeval-tools
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: kubeval
      run:  kubectl kustomize .k8s | kubeval --schema-location https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master

    - name: kube-score
      run:  kubectl kustomize .k8s | kube-score score -
      continue-on-error: true

  create:
    name:    Create manifests
    needs:   [ check ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Kustomize
      uses: multani/action-setup-kustomize@v1

    - name: Render manifests
      run:  kustomize build --output coursemapper-webserver-base.yaml .k8s

    - name: Upload manifests
      uses: actions/upload-artifact@v3
      with:
        name: Kubernetes Manifests
        path: coursemapper-webserver-base.yaml
        if-no-files-found: error
