name: Draft a Release

on:
  push:
    tags: [ v* ]
    branches: [ main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Create draft release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        draft: true
        allowUpdates: true
        updateOnlyUnreleased: true
        skipIfReleaseExists: true
        generateReleaseNotes: true
