name: Draft a Release

on:
  push:
    tags: [ v* ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Create draft release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: true
        allowUpdates: true
        updateOnlyUnreleased: true
        skipIfReleaseExists: true
        generateReleaseNotes: true
