name: Release the application

on:
  workflow_call:

jobs:
  release:
    name: Create Github Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Create draft release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        allowUpdates: true
        updateOnlyUnreleased: true
        skipIfReleaseExists: true
        generateReleaseNotes: true
